In [2]:
import pandas as pd

df = pd.read_csv('../datasets/raw/retrosheet-context.csv')

df.head()

/var/folders/np/f11s751j4dj_y_1cj4yxydpwpsr474/T/ipykernel_62019/483841724.py:3: DtypeWarning: Columns (13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../datasets/raw/retrosheet-context.csv')

,eventID,gameID,event_in_game,inning,visitor_or_home,vis_score,home_score,outs,runner_1b,runner_2b,...,field_2B_playerID,field_3B_playerID,field_SS_playerID,field_LF_playerID,field_CF_playerID,field_RF_playerID,comments,theplay,sh_flag,sf_flag
0,0,BLF191404130,1,1,0,0,0,0,NaN,NaN,...,knabo101,walsj101,doolm101,simmh101,zinng101,meyeb103,"""Hanford first hit in Federal League history.""",S9,False,False
1,1,BLF191404130,2,1,0,0,0,0,hanfc101,NaN,...,knabo101,walsj101,doolm101,simmh101,zinng101,meyeb103,NaN,53/SH,True,False
2,2,BLF191404130,3,1,0,0,0,1,NaN,hanfc101,...,knabo101,walsj101,doolm101,simmh101,zinng101,meyeb103,NaN,3/G,False,False
3,3,BLF191404130,4,1,0,0,0,2,NaN,NaN,...,knabo101,walsj101,doolm101,simmh101,zinng101,meyeb103,NaN,8/F,False,False
4,4,BLF191404130,5,1,1,0,0,0,NaN,NaN,...,downt101,smitf103,loudb101,delaf101,hanfc101,bonil101,NaN,K,False,False

In [3]:
df.describe(include='all')

,eventID,gameID,event_in_game,inning,visitor_or_home,vis_score,home_score,outs,runner_1b,runner_2b,...,field_2B_playerID,field_3B_playerID,field_SS_playerID,field_LF_playerID,field_CF_playerID,field_RF_playerID,comments,theplay,sh_flag,sf_flag
count,1.610758e+07,16107578,1.610758e+07,1.610758e+07,1.610758e+07,1.610758e+07,1.610758e+07,1.610758e+07,5275115,3267960,...,16107578,16107578,16107578,16107578,16107578,16107578,136950,16107578,16107578,16107578
unique,NaN,182770,NaN,NaN,NaN,NaN,NaN,NaN,12997,12148,...,5195,5061,5202,5446,4594,5155,91507,37655,2,2
top,NaN,NYN197409110,NaN,NaN,NaN,NaN,NaN,NaN,rosep001,hendr001,...,morgj001,belta001,vizqo001,bondb001,maysw101,clemr101,"""Mound Visit""",K,False,False
freq,NaN,247,NaN,NaN,NaN,NaN,NaN,NaN,6734,4270,...,105385,118733,115908,115512,115973,92903,20388,1750468,15950419,16015599
mean,8.053788e+06,NaN,4.559672e+01,5.275960e+00,4.925697e-01,2.464793e+00,2.357380e+00,9.381736e-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,4.649857e+06,NaN,2.738922e+01,2.714618e+00,4.999448e-01,2.667275e+00,2.625525e+00,8.226647e-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000e+00,NaN,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,4.026894e+06,NaN,2.300000e+01,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,8.053788e+06,NaN,4.500000e+01,5.000000e+00,0.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.208068e+07,NaN,6.700000e+01,8.000000e+00,1.000000e+00,4.000000e+00,4.000000e+00,2.000000e+00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.610758e+07,NaN,2.470000e+02,2.600000e+01,1.000000e+00,3.000000e+01,2.900000e+01,3.000000e+00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns

Index(['eventID', 'gameID', 'event_in_game', 'inning', 'visitor_or_home',
       'vis_score', 'home_score', 'outs', 'runner_1b', 'runner_2b',
       'runner_3b', 'batterID', 'batter_hand', 'pitch_count', 'pitch_sequence',
       'play_orig', 'pitcherID', 'pitcher_hand', 'field_C_playerID',
       'field_1B_playerID', 'field_2B_playerID', 'field_3B_playerID',
       'field_SS_playerID', 'field_LF_playerID', 'field_CF_playerID',
       'field_RF_playerID', 'comments', 'theplay', 'sh_flag', 'sf_flag'],
      dtype='object')